// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1XVWjpq2opodhNx4pCGewnXUzRTT7MGY',
    appId: '1:123224297236:web:183a95a313c150b0a77c01',
    messagingSenderId: '123224297236',
    projectId: 'appentwickluing',
    authDomain: 'appentwickluing.firebaseapp.com',
    storageBucket: 'appentwickluing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZzcgqOc9SwQ009K7ozQBQuSBZzQK6kHQ',
    appId: '1:123224297236:android:85b9eaa87b4f5cfaa77c01',
    messagingSenderId: '123224297236',
    projectId: 'appentwickluing',
    storageBucket: 'appentwickluing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDGRreZdFkJqz0Eu1UliKqIJtvkvpYCb4',
    appId: '1:123224297236:ios:60ca31a26d4de8fea77c01',
    messagingSenderId: '123224297236',
    projectId: 'appentwickluing',
    storageBucket: 'appentwickluing.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDGRreZdFkJqz0Eu1UliKqIJtvkvpYCb4',
    appId: '1:123224297236:ios:60ca31a26d4de8fea77c01',
    messagingSenderId: '123224297236',
    projectId: 'appentwickluing',
    storageBucket: 'appentwickluing.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1XVWjpq2opodhNx4pCGewnXUzRTT7MGY',
    appId: '1:123224297236:web:402938fd51a98bfca77c01',
    messagingSenderId: '123224297236',
    projectId: 'appentwickluing',
    authDomain: 'appentwickluing.firebaseapp.com',
    storageBucket: 'appentwickluing.firebasestorage.app',
  );
}
